!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem de Cursos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

</head>

<body>
    <div class="container">
        <a class="btn btn-outline-dark" href="/">Voltar</a>
        <a class="btn btn-outline-dark" href="/cursos">Listagem de Cursos</a>
        <a class="btn btn-outline-dark" href="/cursos/novo">Cadastrar novo Curso</a>

                <table class="table">
                    <thead>
                        <th> Nome </th>
                        <th> Status </th>
                       
                    </thead>

                    <tbody>
                        <?php
                            foreach($cursos as $linha){
                                $status = "<span class='badge bg-success'>Ativo</span>";

                                if ($linha['status' == 0]) {
                                  $status = "<span class='badge bg-danger'>Inativo</span>";

                                }
                            echo "
                                <tr>
                                    <td>{$linha['nome']</td>
                                    <td>{$linha['status']</td>
                                </tr>
                            ";
                        }
                        ?>
                    </tbody>
                </table>
            </div>
</body>
</html>