!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem de Cursos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

</head>

<body>
    <div class="container mt-5">
        <a class="btn btn-outline-dark" href="/">Voltar</a>
        <a class="btn btn-outline-dark" href="/cursos">Listagem de Cursos</a>
        <a class="btn btn-dark" href="/cursos/novo">Cadastrar Novo Curso</a>

        <hr>

        <form action="" method="POST">
            <label for="nome">Nome</label>
            <input type="text" name="nome" id="nome" class="form-control"><br>

            <p>Status</p>
            <label for="ativo">Ativo</label>
            <input type="radio" name="status" id="ativo" value="1"><br>

            <label for="ativo">Inativo</label>
            <input type="radio" name="status" id="inativo" value="0"><br>

            <button class="btn btn-primary">Cadastrar novo Curso</button>
        </form>

    </div>
</body>
</html>